### ISSUE TITLE
paste stops working

### ISSUE THREAD

**Issue by jdall** [gazugafan/vscode-indent-on-paste#3]
Having installed this extension, I find that paste stops working. No matter whether pasting using ctrl+V or pasting via the edit menu.
If disabling this extension, paste starts working again.
I've also tried to uninstall and reinstall - the issue persist. 
I just can't get paste to work when indent-on-paste is enabled

Extension version 2.3.2

VSCode details:
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64 (SolydX 9 / Debian Stretch)

Thanks.

**Comment by gazugafan** [comment]
Weird. I'd love to help, but I can't recreate this issue on my end. Everything seems to be working fine for me. We do have some environment differences. Most notably, I'm running VSCode 1.31.1 on Windows 10. Here's my setup...
Version: 1.31.1 (system setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Maybe something was broken in 1.31.0? Or maybe the extension doesn't work in Linux for some reason? I've only tested it on Windows, but the extension uses clipboardy (https://github.com/sindresorhus/clipboardy), which should be fully cross-platform compatible.

Maybe start by upgrading to 1.31.1 and see if that helps? I suppose you could also try switching the ```indentOnPaste.pasteMethod``` preference to ```workaround```, but that really shouldn't be necessary.

**Comment by jdall** [comment]
Version 1.31.1 is not yet available in the packaging system for the distro I'm running, so I can't update for the time being.
But setting indentOnPaste.pasteMethod to "workaround" actually solves the problem.

Thank you very much for your prompt response.

**Comment by gazugafan** [comment]
Weirrrd. I really didn't expect that to work. Hmm... well I'm glad it's working at least. If you come up with any more info, let me know :)

**Comment by jdall** [comment]
Upgraded to 1.31.1 today - it makes no difference to the paste issue

**Comment by gazugafan** [comment]
Thanks for the update. I'm at a loss as to what the problem could be :(

**Comment by Sembiance** [comment]
Same problem with VSCode 1.32.1 on Linux.

Developer tools shows this error:
```
[Extension Host] Error pasting... TypeError: Cannot read property 'end' of undefined
	at handleInput (/home/sembiance/.vscode/extensions/gazugafan.vscode-indent-on-paste-2.3.2/node_modules/execa/index.js:75:17)
	at module.exports (/home/sembiance/.vscode/extensions/gazugafan.vscode-indent-on-paste-2.3.2/node_modules/execa/index.js:273:2)
	at Object.copy (/home/sembiance/.vscode/extensions/gazugafan.vscode-indent-on-paste-2.3.2/node_modules/clipboardy/lib/linux.js:17:10)
	at Object.exports.write.input [as write] (/home/sembiance/.vscode/extensions/gazugafan.vscode-indent-on-paste-2.3.2/node_modules/clipboardy/index.js:28:20)
	at indentOnPaste (/home/sembiance/.vscode/extensions/gazugafan.vscode-indent-on-paste-2.3.2/out/src/extension.js:96:24)
	at t.createApiFactory.C.registerTextEditorCommand.pe.registerCommand.i.edit.e (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:668:416)
	at f.edit (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:429:377)
	at t.createApiFactory.C.registerTextEditorCommand.pe.registerCommand.r (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:668:390)
	at d._executeContributedCommand (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:160)
	at d.$executeContributedCommand (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:534)
	at h._doInvokeHandler (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:593:118)
	at h._invokeHandler (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:777)
	at h._receiveRequest (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:436)
	at h._receiveOneMessage (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:279)
	at define.constructor._protocol.onMessage.e (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:588:565)
	at u.fire (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at e (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:39:64)
	at u.fire (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at s (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:754)
	at Socket.define.constructor._socketDataListener.e (/mnt/compendium/bin/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:960)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

Adding to settings: `"indentOnPaste.pasteMethod": "workaround"` fixed it for me.

**Comment by gazugafan** [comment]
Thanks for the error log! So, the line this is erroring out on is the line where I use clipboardy to replace the contents of your clipboard (with the indent-adjusted version). For some reason, this doesn't work in your environments. Maybe a certain type of Linux environment is the common factor? 

It seems like the bug must be upstream in the clipboardy or execa modules. I'll open a clipboardy issue first and see if they know what's going on.

Setting ```"indentOnPaste.pasteMethod": "workaround"``` fixes this because it changes the mechanism we use to perform the "paste". Instead of overwriting your clipboard and then telling VS Code to paste like normal, we leave your clipboard alone and tell VS Code to insert the modified text directly. The downside to this is that a "paste" action never actually takes place, so any other extensions or re-formatting that should happen "on paste" won't be triggered.

**Comment by Sembiance** [comment]
By the way, my program stats:
```Version: 1.32.1
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:46:10.898Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.6 (Gentoo)

**Comment by gazugafan** [comment]
Cool, thanks! I just mentioned your OS in the clipboardy issue.

**Comment by gazugafan** [comment]
@jdall @Sembiance it seems that the clipboardy devs are having trouble reproducing the issue as well. Can you offer then any more info that might help over at https://github.com/sindresorhus/clipboardy/issues/48 ?

**Comment by Amanpeet** [comment]
i am having same issue. the paste completely stops working.

Version: 1.33.1 (user setup)
OS: Windows 10 x64

**Comment by gazugafan** [comment]
Hmm... haven't seen this happening on Windows before. I wonder if it's the same issue. Does setting ```"indentOnPaste.pasteMethod": "workaround"``` seem to fix the problem, @Galzor ?

**Comment by Amanpeet** [comment]
yes, i tried this workaround solution, it fixes the issue to some extent but also raises problem in another. 
like there are some serious issues when pasting with multicursor.
i request to u plz enable some customization options for plugin plz. rather than hijacking the default paste functionality of vscode, may a shortcut only option is better like sublime where we can ctrl+shift+v to indent paste.
1 more thing, whenever i paste with plugin enabled, it shows Activating Extension message in status bar and than pastes after little delay, without plugin its instant. it aint much problem but it feels slower.

**Comment by gazugafan** [comment]
Thanks for the report, Galzor. Unfortunately, I haven't been able to reproduce these problems.

You said pasting "stops working"... does that mean it was working at one point? If so, does it seem to stop working for any reason? Do you get an error in the extension logs when you try to paste and it doesn't work? You should be able to see the logs with ```CTRL+SHIFT+P > Show Logs > Extension Host```.

What issues are you having with multicursor pasting?

**Comment by gazugafan** [comment]
Oh, actually I think I see the multicursor issues. Trying to paste when you have multiple selections only pastes to the first selection. It's not a feature I ever use, but I'll see what I can do to better support it soon.

**Comment by Amanpeet** [comment]
yes, it works only when i simple copy paste the code, like html in html file, but it stops pasting entirely when i work with mixed content like php files containing html, css, js, php code all mixed up. not everytime but many times. 
and the multicursor issue, well u know it now.
my suggestion is to go with the shortcut system rather than hijacking clipboard system.

**Comment by gazugafan** [comment]
I could certainly add a new paste command that you could bind to a hotkey, and an option to disable the native paste hijack. No idea if that would solve your problem, though. I'd love to know why it's not working to begin with. Were you able to grab an error log?

Breaking off the multicursor problem to issue #6 and the paste command feature to #5.

**Comment by Amanpeet** [comment]
hi gazugafan, i wud love to work with you to solve this issue. but i am on holiday for few days and wont be able to grab log from my office pc. will paste here as soon as i get my hands on it.

**Comment by gazugafan** [comment]
@jdall @Sembiance I think I've gotten to the bottom of the Linux pasting problem. Looks like clipboardy relied on a packaged Linux executable that was losing it's execute permission because I was publishing from Windows. I think just publishing from Linux going forward should solve the problem. Can you give v2.3.3 a try and report back?

**Comment by jdall** [comment]
With version 2.3.3, pasting is working on my system (Linux SolydX 9 / Debian 9), whether paste method is native or workaround.

**Comment by Sembiance** [comment]
I can verify that v2.3.3 works great :)
